version: 2

project_name: stackctl

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: stackctl
    main: ./...
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/subrotokumar/stackctl/v4/cmd/core.Version=v{{.Version}}
      - -s -w -X github.com/subrotokumar/stackctl/v4/cmd/core.Commit={{.Commit}}
      - -s -w -X github.com/subrotokumar/stackctl/v4/cmd/core.Date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x

upx:
  # Linux: amd64, arm64, 386
  - enabled: true
    ids: [default]
    goos: [linux]
    goarch: [amd64, arm64, "386"]
    compress: best
    lzma: true

  # Windows: amd64, 386 (UPX doesn't support windows/arm64)
  - enabled: true
    ids: [default]
    goos: [windows]
    goarch: [amd64, "386"]
    compress: best
    lzma: true

archives:
  - formats: [tar.gz]
    # OS and arch names match the output of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Use zip for Windows archives.
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
